{{- if .Values.newrelic.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "blazegraph.name" . }}
    chart: {{ template "blazegraph.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "blazegraph.fullname" . }}-newrelic
type: Opaque
data:
  key: {{ ( printf "%s" .Values.newrelic.licenseKey ) | b64enc }}
{{- end }}
